ALTER TABLE vacancy ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE resume ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE event ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending';
